//
//  Mockata.swift
//  CleanArchitectureSampleCodeTest
//
//  Created by Victor on 2021/5/3.
//

import Foundation

@testable import BookMyMovie
class Mockata {
    static let movieListJson = "{\n    \"page\": 1,\n    \"results\": [\n        {\n            \"adult\": false,\n            \"backdrop_path\": \"/y3XMIea7mwTzxt3NFFXi5YJKeFJ.jpg\",\n            \"genre_ids\": [\n                10751,\n                28,\n                16,\n                12,\n                14\n            ],\n            \"id\": 20982,\n            \"original_language\": \"ja\",\n            \"original_title\": \"劇場版 NARUTO -ナルト- 疾風伝\",\n            \"overview\": \"Demons that once almost destroyed the world, are revived by someone. To prevent the world from being destroyed, the demon has to be sealed and the only one who can do it is the shrine maiden Shion from the country of demons, who has two powers; one is sealing demons and the other is predicting the deaths of humans. This time Naruto's mission is to guard Shion, but she predicts Naruto's death. The only way to escape it, is to get away from Shion, which would leave her unguarded, then the demon, whose only goal is to kill Shion will do so, thus meaning the end of the world. Naruto decides to challenge this \\\"prediction of death.\\\"\",\n            \"popularity\": 386.16,\n            \"poster_path\": \"/vDkct38sSFSWJIATlfJw0l3QOIR.jpg\",\n            \"release_date\": \"2007-08-04\",\n            \"title\": \"Naruto Shippuden the Movie\",\n            \"video\": false,\n            \"vote_average\": 7.1,\n            \"vote_count\": 308\n        },\n        {\n            \"adult\": false,\n            \"backdrop_path\": \"/eAISoFMi29BVBKH1VRpne4mJ26K.jpg\",\n            \"genre_ids\": [\n                27,\n                53\n            ],\n            \"id\": 227348,\n            \"original_language\": \"en\",\n            \"original_title\": \"Paranormal Activity: The Marked Ones\",\n            \"overview\": \"Seventeen-year-old Jesse has been hearing terrifying sounds coming from his neighbor’s apartment, but when he turns on his camera and sets out to uncover their source, he encounters an ancient evil that won’t rest until it’s claimed his very soul.\",\n            \"popularity\": 190.116,\n            \"poster_path\": \"/4srdg5SoxREXha5kibwZBvsqNtV.jpg\",\n            \"release_date\": \"2014-01-01\",\n            \"title\": \"Paranormal Activity: The Marked Ones\",\n            \"video\": false,\n            \"vote_average\": 5.4,\n            \"vote_count\": 1036\n        }],\n    \"total_pages\": 500,\n    \"total_results\": 10000\n}"
    
    static let movieDetailJson = "{\n    \"adult\": false,\n    \"backdrop_path\": \"/y3XMIea7mwTzxt3NFFXi5YJKeFJ.jpg\",\n    \"belongs_to_collection\": {\n        \"id\": 23616,\n        \"name\": \"Naruto Collection\",\n        \"poster_path\": \"/q9rrfRgPUFkFqDF74jlvNYp3RpN.jpg\",\n        \"backdrop_path\": \"/prLI2SNNkd9wcQkFh9iWXzQtR5D.jpg\"\n    },\n    \"budget\": 29000000,\n    \"genres\": [\n        {\n            \"id\": 10751,\n            \"name\": \"Family\"\n        },\n        {\n            \"id\": 28,\n            \"name\": \"Action\"\n        },\n        {\n            \"id\": 16,\n            \"name\": \"Animation\"\n        },\n        {\n            \"id\": 12,\n            \"name\": \"Adventure\"\n        },\n        {\n            \"id\": 14,\n            \"name\": \"Fantasy\"\n        }\n    ],\n    \"homepage\": \"http://www.naruto-movie.com/\",\n    \"id\": 20982,\n    \"imdb_id\": \"tt0988982\",\n    \"original_language\": \"ja\",\n    \"original_title\": \"劇場版 NARUTO -ナルト- 疾風伝\",\n    \"overview\": \"Demons that once almost destroyed the world, are revived by someone. To prevent the world from being destroyed, the demon has to be sealed and the only one who can do it is the shrine maiden Shion from the country of demons, who has two powers; one is sealing demons and the other is predicting the deaths of humans. This time Naruto's mission is to guard Shion, but she predicts Naruto's death. The only way to escape it, is to get away from Shion, which would leave her unguarded, then the demon, whose only goal is to kill Shion will do so, thus meaning the end of the world. Naruto decides to challenge this \\\"prediction of death.\\\"\",\n    \"popularity\": 386.16,\n    \"poster_path\": \"/vDkct38sSFSWJIATlfJw0l3QOIR.jpg\",\n    \"production_companies\": [\n        {\n            \"id\": 3234,\n            \"logo_path\": \"/o17H0aZzAn0qgVHY2IO3oDXVoBH.png\",\n            \"name\": \"Pierrot\",\n            \"origin_country\": \"JP\"\n        }\n    ],\n    \"production_countries\": [\n        {\n            \"iso_3166_1\": \"JP\",\n            \"name\": \"Japan\"\n        }\n    ],\n    \"release_date\": \"2007-08-04\",\n    \"revenue\": 0,\n    \"runtime\": 94,\n    \"spoken_languages\": [\n        {\n            \"english_name\": \"Japanese\",\n            \"iso_639_1\": \"ja\",\n            \"name\": \"日本語\"\n        }\n    ],\n    \"status\": \"Released\",\n    \"tagline\": \"\",\n    \"title\": \"Naruto Shippuden the Movie\",\n    \"video\": false,\n    \"vote_average\": 7.1,\n    \"vote_count\": 308\n}"
}
